name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js version 18 using NVM
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 18
          nvm use 18
          node -v

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            # Check if Node is installed and install it if not
            if ! command -v node &> /dev/null
            then
                curl -sL https://deb.nodesource.com/setup_18.x | sudo bash -
                sudo apt install -y nodejs
            fi

            cd /var/www/no-game.xyz/nogame-app
            git pull origin master

            # Check for npm command
            if command -v npm &> /dev/null
            then
                npm install
                echo '${{ secrets.BACKEND_ENV_FILE }}' > packages/backend/.env
                echo '${{ secrets.FRONTEND_ENV_FILE }}' > packages/frontend/.env

                # Build Frontend
                cd packages/frontend
                npm install
                npm run build

                # Build Backend
                cd ../backend
                npm install
                npm run build

                # Restart the application using PM2
                cd /var/www/no-game.xyz/nogame-app
                pm2 restart all
            else
                echo "npm not found"
            fi
